IPOR Protocol - Arbitrum swaps volume
DefiLlama/dimension-adapters pull request #1244
Opened 2024-02-27 14:33 UTC by amydlarz

2024-02-27 14:34 UTC, llamatester commented
The ipor adapter exports: 
        
 
 _______________________________________
    Dexs for 26/2/2024
    _______________________________________
    
    Version -> DERIVATIVES
    ---------
    ETHEREUM 👇
    Backfill start time: 16/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1708991999 (2024-02-26T23:59:59.000Z)
    Daily volume: 0
    
    
    ARBITRUM 👇
    Backfill start time: 21/2/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1708991999 (2024-02-26T23:59:59.000Z)
    Daily volume: 0
    
    
    Done in 8.13s.

2024-02-27 14:37 UTC, amydlarz commented
For 2024-02-26 returns balance
```
{
  chain: 'arbitrum',
  timestamp: undefined,
  _balances: { '0x5979D7b546E38E414F7E9822514be443A4800529': 3.9447389885807502 }
}
```
but daily volume is 0. Is it correct?

2024-02-27 15:03 UTC, dtmkeng requested changes

2024-02-27 15:03 UTC, dtmkeng commented on dexs/ipor/index.ts
> +    dailyNotionalVolume.addToken(log.asset, balance / 1e18, { skipChain: true })
fix this with `dailyNotionalVolume.add(log.asset, balance)`

2024-02-28 07:27 UTC, llamatester commented
The ipor adapter exports: 
        
 
 _______________________________________
    Dexs for 27/2/2024
    _______________________________________
    
    Version -> DERIVATIVES
    ---------
    ETHEREUM 👇
    Backfill start time: 16/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709078399 (2024-02-27T23:59:59.000Z)
    Daily volume: 0
    
    
    ARBITRUM 👇
    Backfill start time: 21/2/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709078399 (2024-02-27T23:59:59.000Z)
    Daily volume: 0
    
    
    Done in 11.58s.

2024-02-28 07:28 UTC, llamatester commented
The ipor adapter exports: 
        
 
 _______________________________________
    Dexs for 27/2/2024
    _______________________________________
    
    Version -> DERIVATIVES
    ---------
    ETHEREUM 👇
    Backfill start time: 16/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709078399 (2024-02-27T23:59:59.000Z)
    Daily volume: 0
    
    
    ARBITRUM 👇
    Backfill start time: 21/2/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709078399 (2024-02-27T23:59:59.000Z)
    Daily volume: 0
    
    
    Done in 9.79s.

2024-02-28 07:29 UTC, llamatester commented
The ipor adapter exports: 
        
 
 _______________________________________
    Dexs for 27/2/2024
    _______________________________________
    
    Version -> DERIVATIVES
    ---------
    ETHEREUM 👇
    Backfill start time: 16/8/2022
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709078399 (2024-02-27T23:59:59.000Z)
    Daily volume: 0
    
    
    ARBITRUM 👇
    Backfill start time: 21/2/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1709078399 (2024-02-27T23:59:59.000Z)
    Daily volume: 671.51 k
    
    
    Done in 9.10s.

2024-02-28 14:19 UTC, merged