Rubic aggregator
DefiLlama/dimension-adapters pull request #1291
Opened 2024-03-12 13:41 UTC by Doctor-Cyclone

Created [Rubic](https://app.rubic.exchange/) volume adapter.

2024-03-12 15:00 UTC, dtmkeng commented
your volume is count volume it go to other agg like 1inch ?

2024-03-13 08:00 UTC, Doctor-Cyclone commented
- We have multi-proxy-rubic contracts. Explorer (https://etherscan.io/address/0x3335733c454805df6a77f825f266e136fb4a3333)
- Users come to our app. They make a swap. The swap goes through our contracts and only then through 1inch.
That is, we, as aggregators, use providers, but the volumes and users are ours, and they go through our contracts. We take into account the volumes of our contracts only.

2024-03-13 08:09 UTC, dtmkeng commented
> * We have multi-proxy-rubic contracts. [Explorer](https://etherscan.io/address/0x3335733c454805df6a77f825f266e136fb4a3333)
> * Users come to our app. They make a swap. The swap goes through our contracts and only then through 1inch.
>   That is, we, as aggregators, use providers, but the volumes and users are ours, and they go through our contracts. We take into account the volumes of our contracts only.

how to exclude volume is go to other agg if list it double count with other dexs agg like 1inch

2024-03-13 09:09 UTC, Doctor-Cyclone commented
Our volumes include volumes from 1inch and other aggregators if they were conducted through our proxy. No need to exclude anything

2024-03-13 09:26 UTC, dtmkeng commented
could you count volume go to dexs not agge dexs like 1 inch

2024-03-13 09:32 UTC, Doctor-Cyclone commented
Did not understand
Move the folder to Dex and not to aggregators?

2024-03-13 09:45 UTC, dtmkeng commented
no i mean your api it count other agg volume ex 1 inch if list it double count. can you exclude other agg on your api

2024-03-13 10:09 UTC, Doctor-Cyclone commented
Can you please tell me in more detail where the double count is? With us, all volumes pass through a proxy, without dividing providers into aggregator/non-aggregator

2024-03-13 14:32 UTC, dtmkeng commented
> Can you please tell me in more detail where the double count is? With us, all volumes pass through a proxy, without dividing providers into aggregator/non-aggregator

Rubic is aggerator protocol and you tell me Rubic have some go too 1inch then this api `https://api.rubic.exchange/api/stats/defilama_onchain?dat` is include volume that go to 1inch right ? 
we can't list if you count volume that go to dexs agg intead dexs (uniswap, pancake...)

2024-03-14 09:15 UTC, asdener123 commented
> > Can you please tell me in more detail where the double count is? With us, all volumes pass through a proxy, without dividing providers into aggregator/non-aggregator
> 
> Rubic is aggerator protocol and you tell me Rubic have some go too 1inch then this api `https://api.rubic.exchange/api/stats/defilama_onchain?dat` is include volume that go to 1inch right ? we can't list if you count volume that go to dexs agg intead dexs (uniswap, pancake...)

Hey, could you please provide further details on why we should exclude DEX aggregators like 1inch from our volume calculations?
Our team strongly believes in including 1inch in our metrics, given its significant usage among Rubic users. Moreover, as a DEX aggregator ourselves, we're aggregating the best DEXs and Aggregators in our platform. 
As explained by @Doctor-Cyclone, we employ proxy contracts for each DEX or DEX aggregator, allowing us to earn commissions from swaps conducted through these platforms.
Excluding this data could result in inaccurate submissions to Defilama, affecting our volume, commissions, and ultimately misleading our users. Greatly appreciate any means to retain this data.
You can find the complete list of our integrated DEXs here: https://docs.rubic.finance/rubic/rubics-ecosystem

2024-03-14 23:54 UTC, Define101 commented
Hello @asdener123 and @Doctor-Cyclone 
To give you some context, we have 3 products relating to volume.
1- Normal volume (aka overview page) this is volume coming from swaps (dexes)
2- Derivatives volume (aka derivatives page) this is volume with leverage (basically, if there is leverage involved)
3- Dex aggregators volume (aka aggregators page), this is volume coming ONLY from dexes aggregators (witch themself use dexes, not other dexes aggregator)

Your product is a mix of dexes aggregator and a dexes aggregator aggregator (the product we have called llamaswap is a dexes aggregator aggregator) . For that reason, we don't track llamaswap volume since that volume is being tracked under the aggregators we use. With this in mind, there are 2 alternatives for rubi:
1)  We track ONLY volume coming from dexes (meaning your dexes aggregator product), and NOT the volume coming from dexes aggregators (like 1inch,paraswap e.t.c)2)  We don't track nothing

2024-03-15 00:07 UTC, Define101 commented
"Excluding this data could result in inaccurate submissions to Defilama, affecting our volume, commissions, and ultimately misleading our users. Greatly appreciate any means to retain this data." 

I understand this, but we can't break our own rules. We can maybe add a disclaimer, or something informing the user that we are only tracking your dex agg product and not the dex aggre aggre

2024-05-09 09:15 UTC, llamatester commented
The rubic adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

2024-05-09 09:19 UTC, Doctor-Cyclone commented
@Define101 
Hello, we are back to the process of adding Rubic to the DefiLlama. But when I try to run tests through the `yarn test aggregators rubic` command, I get the following error: `ERROR: Use Adapter v2 format for new adapters`

2024-05-09 09:21 UTC, Doctor-Cyclone commented
We also excluded the following aggregators from our indicators: `openocean, xy_dex,  symbiosis, odos, lifi, rango, oneinch`

2024-05-09 13:22 UTC, dtmkeng requested changes

2024-05-09 13:22 UTC, dtmkeng commented on aggregators/rubic/index.ts
> +  adapter: {
add `version: 2` adove `adapter`

2024-05-09 14:38 UTC, Doctor-Cyclone commented on aggregators/rubic/index.ts
> +  adapter: {
Done.

2024-05-09 15:15 UTC, merged