feat: add Slipstream volume + fees
DefiLlama/dimension-adapters pull request #1431
Opened 2024-04-22 18:29 UTC by ethzoomer

Based the code off of `dexs/aerodrome`. Verified the outputted numbers with Velodrome Sugar repo results and Velodrome UI

2024-04-22 18:29 UTC, llamatester commented
The velodrome-slipstream adapter exports: 
        
 
 _______________________________________
    Dexs for 21/4/2024
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 6/3/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 30.35 M
    Timestamp: 1713743999 (2024-04-21T23:59:59.000Z)
    
    
    
    
    Done in 16.59s.

2024-04-22 18:30 UTC, llamatester commented
The velodrome-slipstream adapter exports: 
        
 
 _______________________________________
    Fees for 21/4/2024
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 6/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 14.43 k
    Timestamp: 1713743999 (2024-04-21T23:59:59.000Z)
    Daily revenue: 14.43 k
    Daily holders revenue: 14.43 k
    
    
    
    
    Done in 7.22s.

2024-04-23 12:21 UTC, 0xngmi commented on dexs/velodrome-slipstream/index.ts
> +      dailyVolume.add(token0, BigInt(Math.abs(Number(log.amount0))))
doesnt this doublecount volume?

2024-04-23 12:21 UTC, dtmkeng requested changes

2024-04-23 12:21 UTC, dtmkeng commented on dexs/velodrome-slipstream/index.ts
> +      dailyVolume.add(token0, BigInt(Math.abs(Number(log.amount0))))
this line is double count volume it should only one `amount1` or `amount0`

2024-04-23 13:02 UTC, llamatester commented
The velodrome-slipstream adapter exports: 
        
 
 _______________________________________
    Dexs for 22/4/2024
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 6/3/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 15.94 M
    Timestamp: 1713830399 (2024-04-22T23:59:59.000Z)
    
    
    
    
    Done in 18.35s.

2024-04-23 13:02 UTC, llamatester commented
The velodrome-slipstream adapter exports: 
        
 
 _______________________________________
    Fees for 22/4/2024
    _______________________________________
    
    OPTIMISM 👇
    Backfill start time: 6/3/2024
    NO METHODOLOGY SPECIFIED
    Daily fees: 10.88 k
    Timestamp: 1713830399 (2024-04-22T23:59:59.000Z)
    Daily revenue: 10.88 k
    Daily holders revenue: 10.88 k
    
    
    
    
    Done in 7.02s.

2024-04-23 13:05 UTC, ethzoomer commented on dexs/velodrome-slipstream/index.ts
> +      dailyVolume.add(token0, BigInt(Math.abs(Number(log.amount0))))
Yes ty fixed

2024-04-23 15:21 UTC, merged