add bitlayer fees adapter
DefiLlama/dimension-adapters pull request #1467
Opened 2024-05-07 14:09 UTC by stromman

we creat a adapter for bitlayer project
PLS check and fallback for fees/bitlayer/index.ts

2024-05-07 14:12 UTC, dtmkeng commented
could you resolve conflicts

2024-05-07 14:16 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

2024-05-07 14:20 UTC, dtmkeng requested changes

2024-05-07 14:20 UTC, dtmkeng commented on fees/bitlayer/index.ts
> +  adapter: {
add `version: 2` above `adapter`

2024-05-07 14:20 UTC, dtmkeng commented on fees/bitlayer/index.ts
> +        console.log("amount", amount);
remove console log

2024-05-07 14:20 UTC, dtmkeng commented on fees/bitlayer/index.ts
> +      },
add `runAtCurrTime: true` above `start`

2024-05-07 14:28 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    Fees for 7/5/2024
    _______________________________________
    
    TypeError: Cannot destructure property 'startOfDay' of 'undefined' as it is undefined.
        at getEtherscanFees (/home/runner/work/dimension-adapters/dimension-adapters/fees/bitlayer/index.ts:40:5)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/bitlayer/index.ts:68:30)
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:25)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bitlayer'
    }

2024-05-07 14:30 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    Fees for 7/5/2024
    _______________________________________
    
    TypeError: Cannot destructure property 'startOfDay' of 'undefined' as it is undefined.
        at getEtherscanFees (/home/runner/work/dimension-adapters/dimension-adapters/fees/bitlayer/index.ts:40:5)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/bitlayer/index.ts:68:30)
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:25)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bitlayer'
    }

2024-05-07 14:31 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    Fees for 7/5/2024
    _______________________________________
    
    TypeError: Cannot destructure property 'startOfDay' of 'undefined' as it is undefined.
        at getEtherscanFees (/home/runner/work/dimension-adapters/dimension-adapters/fees/bitlayer/index.ts:40:5)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/bitlayer/index.ts:68:30)
        at getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:25)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'bitlayer'
    }

2024-05-07 15:07 UTC, dtmkeng requested changes

2024-05-07 15:07 UTC, dtmkeng commented on fees/bitlayer/index.ts
> +        options: FetchOptions
param should only (options: FetchOptions)

2024-05-07 15:15 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    Fees for 7/5/2024
    _______________________________________
    
    [Error: Request failed with status code 429] {
      url: 'https://api.btrscan.com/scan/v1/chain/txForDefillama',
      method: 'POST',
      axiosError: 'Too Many Requests',
      chain: 'bitlayer'
    }

2024-05-07 15:22 UTC, dtmkeng commented
seem api error

2024-05-07 15:24 UTC, stromman commented
> seem api error
Frequency Limit

2024-05-07 15:31 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    Fees for 7/5/2024
    _______________________________________
    
    [Error: Request failed with status code 429] {
      url: 'https://api.btrscan.com/scan/v1/chain/txForDefillama',
      method: 'POST',
      axiosError: 'Too Many Requests',
      chain: 'bitlayer'
    }

2024-05-07 15:31 UTC, dtmkeng commented
still error could you check

2024-05-07 15:34 UTC, llamatester commented
The bitlayer.ts adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

2024-05-07 15:34 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

2024-05-07 15:38 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    Fees for 7/5/2024
    _______________________________________
    
    BITLAYER 👇
    Backfill start time: 14/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1715094481 (2024-05-07T15:08:01.000Z)
    Daily fees: 0

2024-05-07 15:58 UTC, dtmkeng commented
is there probby some day return daily fees is 0  ?

2024-05-07 16:03 UTC, stromman commented
> is there probby some day return daily fees is 0 ?

nop, something wrong.repairing

2024-05-08 04:32 UTC, AoWangg commented
@dtmkeng Dear reviewer, please re-examine this code as we have addressed the issues previously pointed out.

2024-05-08 15:05 UTC, dtmkeng commented
> @dtmkeng Dear reviewer, please re-examine this code as we have addressed the issues previously pointed out. Thank you very much.

it is this web https://www.bitlayer.org/gas-swap ?

2024-05-09 06:15 UTC, stromman commented
> Dear reviewer, please re-examine this code as we have addressed the issues previously pointed out. Thank you very much.

I thank that you mean : https://www.btrscan.com/

2024-05-09 06:33 UTC, AoWangg commented
> > @dtmkeng Dear reviewer, please re-examine this code as we have addressed the issues previously pointed out. Thank you very much.
> 
> it is this web https://www.bitlayer.org/gas-swap ?

Thanks for the merge.

Here is some information about Bitlayer

**Website:** https://www.bitlayer.org/
**Twitter:** https://twitter.com/BitLayerLabs

2024-05-09 13:20 UTC, merged

2024-05-09 14:15 UTC, llamatester commented
The bitlayer adapter exports: 
        
 
 _______________________________________
    Fees for 9/5/2024
    _______________________________________
    
    BITLAYER 👇
    Backfill start time: 14/4/2024
    NO METHODOLOGY SPECIFIED
    Timestamp: 1715262340 (2024-05-09T13:45:40.000Z)
    Daily fees: 5.37 k

2024-05-09 14:24 UTC, dtmkeng commented
hmm why i call at my local it error 
```
[Error: connect ETIMEDOUT 2606:4700:20::681a:4ac:443] {
  url: 'https://api.btrscan.com/scan/v1/chain/txForDefillama',
  method: 'POST',
  chain: 'bitlayer'
}
```