total and daily revenue for flash.trade
DefiLlama/dimension-adapters pull request #1522
Opened 2024-05-26 08:57 UTC by UjjwalGupta49

adapter to showcase daily aggregrated revenue and 24 hour aggregated revenue for flash.trade

2024-05-26 08:57 UTC, llamatester commented
The flashtrade.ts adapter exports: 
        
 
 _______________________________________
    
    
    
    ERROR: Use Adapter v2 format for new adapters

2024-05-26 13:05 UTC, dtmkeng requested changes

2024-05-26 13:05 UTC, dtmkeng commented on fees/flashtrade.ts
> +    adapter: {
add `version: 2` above `adapter`

2024-05-29 09:25 UTC, llamatester commented
The flashtrade.ts adapter exports: 
        
 
 _______________________________________
    Fees for 29/5/2024
    _______________________________________
    
    SOLANA 👇
    Backfill start time not defined
    Timestamp: 1716972947 (2024-05-29T08:55:47.000Z)
    Daily protocol revenue: 29.13 k
    Total protocol revenue: 2.57 M

2024-05-29 09:26 UTC, UjjwalGupta49 commented on fees/flashtrade.ts
> +    adapter: {
i've added adapter version 2

2024-05-29 16:50 UTC, dtmkeng commented
how many fees ?

2024-06-01 16:02 UTC, UjjwalGupta49 commented
@dtmkeng what does that mean?

> how many fees ?

2024-06-01 16:22 UTC, dtmkeng commented
> @dtmkeng what does that mean?
> 
> > how many fees ?

fees is require field `dailyFees`

2024-06-01 16:56 UTC, UjjwalGupta49 commented
can you share a reference or a similar example?

2024-06-01 17:16 UTC, dtmkeng commented
> can you share a reference or a similar example?

 https://docs.llama.fi/analysts/data-definitions docs

2024-06-04 11:42 UTC, llamatester commented
The flashtrade.ts adapter exports: 
        
 
 _______________________________________
    Fees for 4/6/2024
    _______________________________________
    
    TypeError: Cannot read properties of undefined (reading 'reduce')
        at fetchFlashStats (/home/runner/work/dimension-adapters/dimension-adapters/fees/flashtrade.ts:32:37)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:31:18)
        at async Promise.all (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:75:21 {
      chain: 'solana'
    }

2024-06-04 12:54 UTC, dtmkeng requested changes

2024-06-04 12:54 UTC, dtmkeng commented on fees/flashtrade.ts
> +    const totalStats: Pool[] = totalStatsResponse.data;
could you remove `.data` fetchURL is `.data` already

2024-06-04 14:52 UTC, merged

2024-06-12 09:26 UTC, UjjwalGupta49 commented
hey @dtmkeng the fees and revenue for flashtrade are different - fees is the 100% of the value and revenue is 30% of fees, the same is being given as input to the adapters for fees and revenue but on the UI is shows fees and revenue as the same. Please have a look

Thanks
![image](https://github.com/DefiLlama/dimension-adapters/assets/83765858/43852b2f-3872-46e1-b69a-fc174037a010)

2024-06-12 11:13 UTC, dtmkeng commented
let me check

2024-06-27 13:53 UTC, UjjwalGupta49 commented
hi there @dtmkeng - there's a recent issue with the volume shown on defilama

it's been showing the same volume for the past three days, please have a look to the issue - thanks.
![image](https://github.com/DefiLlama/dimension-adapters/assets/83765858/8dbbfd63-903c-4a4d-9c1e-7b6395811168)
![image](https://github.com/DefiLlama/dimension-adapters/assets/83765858/aa81d832-24d6-49c3-a915-7d82cc1bae51)

2024-06-27 14:14 UTC, dtmkeng commented
> hi there @dtmkeng - there's a recent issue with the volume shown on defilama
> 
> it's been showing the same volume for the past three days, please have a look to the issue - thanks. ![image](https://private-user-images.githubusercontent.com/83765858/343804129-8dbbfd63-903c-4a4d-9c1e-7b6395811168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTc5NjksIm5iZiI6MTcxOTQ5NzY2OSwicGF0aCI6Ii84Mzc2NTg1OC8zNDM4MDQxMjktOGRiYmZkNjMtOTAzYy00YTRkLTljMWUtN2I2Mzk1ODExMTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNzMyNDhlM2IzZDg5MjUyMzVlYzBiYTRkZmNmYjIyZjM2YjNmNTZjYTcyM2FlMmZlM2FkZTU4NTVhNWYzZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9-UsukYmrOg-iLR2-AE8jkam9xGMlK4Gmakhwvqbh-w) ![image](https://private-user-images.githubusercontent.com/83765858/343804385-aa81d832-24d6-49c3-a915-7d82cc1bae51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTc5NjksIm5iZiI6MTcxOTQ5NzY2OSwicGF0aCI6Ii84Mzc2NTg1OC8zNDM4MDQzODUtYWE4MWQ4MzItMjRkNi00OWMzLWE5MTUtN2Q4MmNjMWJhZTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE0MTQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjNhM2ViZmIxYzYxOGY5ZjA4MDdjYjk3ZWQwMDFmNmM0ZTk4MDA3ODg4ZmQyNGRlYWJiNjU0OTgxM2M5NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LmPArWRZ3Do4laQGEsjxvwl1kpcShI7SmlYX5nWH-aI)

your api it error

[Error: Request failed with status code 403] {
  url: 'https://api.prod.flash.trade/market-stat/revenue-all-time',
  method: 'GET',
  axiosError: 'Forbidden',
  chain: 'solana'
}

2024-06-27 14:47 UTC, UjjwalGupta49 commented
can you please share you server IP?

2024-06-27 15:02 UTC, dtmkeng commented
> can you please share your server IP?

can't we don't have static ip

2024-06-28 09:15 UTC, UjjwalGupta49 commented
we've updated the endpoint can you please try a re-deployment if that's necessary to update the volume stats.

2024-06-28 14:10 UTC, dtmkeng commented
do you have historical data ? will help refil missing  data

2024-07-15 04:13 UTC, UjjwalGupta49 commented
hey there @dtmkeng on the defillama dashboard for flashtrade th data for fees, volume and revenue looks stale - can you please share the logs to help us better understand the issue.

Thanks you

2024-07-15 13:34 UTC, dtmkeng commented
which day is not correct ?

2024-07-18 10:05 UTC, UjjwalGupta49 commented
it was stale from July 9 th to 13 th for the volume

2024-07-18 12:44 UTC, dtmkeng commented
is there historical data will refill ?

2024-07-19 09:20 UTC, UjjwalGupta49 commented
heres the historiacal data for july 9 to 13 th for deratives volume that was stale -

(values in USD)

2024-07-13 | 18995116.77
2024-07-12 | 41234564.86
2024-07-11 | 102161933.5
2024-07-10 | 103746078
2024-07-09 | 149999449.6

2024-07-19 12:38 UTC, UjjwalGupta49 commented
also the volume has been stale for the past two days (17, 18) th of july - can you please share the logs for us to improve upon the API.

2024-09-13 16:15 UTC, UjjwalGupta49 commented
Hey there @dtmkeng the derivatives volume seems to be stagnated from the past few days for flash.trade, we have the correct data to back full stats on our defilama page. Please have look and let me know how can backfill the missing data for volume.
![Uploading Screenshot_20240913-214315.png…]()

2024-09-13 16:15 UTC, UjjwalGupta49 commented
Hey there @dtmkeng the derivatives volume seems to be stagnated from the past few days for flash.trade, we have the correct data to back full stats on our defilama page. Please have look and let me know how can backfill the missing data for volume.
![Screenshot_20240913-214315](https://github.com/user-attachments/assets/ec3fdc35-6e07-440e-8392-79eb18fc4887)