7k aggregator volume statistic
DefiLlama/dimension-adapters pull request #1653
Opened 2024-07-08 07:16 UTC by tuanh2000

7k is an aggregator build on SUI blockchain

2024-07-08 07:17 UTC, llamatester commented
The 7k-aggregator adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators 7k-aggregator
    
    🦙 Running 7K-AGGREGATOR adapter 🦙
    ---------------------------------------------------
    
    
    
    ERROR: Use Adapter v2 format for new adapters

2024-07-08 07:29 UTC, tuanh2000 commented
what should I do? I don't know what this error means.

2024-07-08 13:58 UTC, dtmkeng requested changes

2024-07-08 13:58 UTC, dtmkeng commented on aggregators/7k-aggregator/index.ts
> +	adapter: {
add `version: 2` above `adapter`

2024-07-08 14:04 UTC, tuanh2000 commented
Maybe we got another error, why timestamp is an object bro?

2024-07-08 14:06 UTC, tuanh2000 commented
oh, I know what happened here, let me fix it

2024-07-08 14:46 UTC, llamatester commented
The 7k-aggregator adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators 7k-aggregator
    
    🦙 Running 7K-AGGREGATOR adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 07 Jul 2024 14:16:23 GMT
    End Date:	Mon, 08 Jul 2024 14:16:23 GMT
    ---------------------------------------------------
    
    SUI 👇
    Backfill start time: 28/6/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 1
    End timestamp: 1720448182 (2024-07-08T14:16:22.000Z)

2024-07-08 14:48 UTC, tuanh2000 commented
https://1drv.ms/f/c/4f8f7df9b045821e/Epbf9TKmQbZGsuviSWDDuE0Bkwk_P5tXt76mIG_sIYlt3w?e=oFFp8L
This is out logo, let's check the request one last time, I think it worked.

2024-07-10 14:20 UTC, tuanh2000 commented
website: https://7k.ag
twitter: https://twitter.com/7k_ag_

2024-07-10 15:13 UTC, merged