feat: add floki-trading-bot dimension adapter
DefiLlama/dimension-adapters pull request #1927
Opened 2024-09-19 08:36 UTC by JCollinsX

2024-09-19 08:37 UTC, llamatester commented
The floki-trading-bot.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees floki-trading-bot.ts
    
    🦙 Running FLOKI-TRADING-BOT.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 18 Sep 2024 08:06:30 GMT
    End Date:	Thu, 19 Sep 2024 08:06:30 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/4082749/execute',
      method: 'POST',
      axiosError: 'invalid API Key',
      chain: 'bsc'
    }

2024-09-23 22:14 UTC, 0xngmi requested changes

2024-09-23 22:14 UTC, 0xngmi commented on fees/floki-trading-bot.ts
> +  const rows = (await queryDune(duneQueryId[options.chain], {
pls use query dune sql instead, or if youre just counting money that goes to an address you can use the function we use in other tg bot adapters

2024-09-24 20:26 UTC, llamatester commented
The floki-trading-bot.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees floki-trading-bot.ts
    
    🦙 Running FLOKI-TRADING-BOT.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 23 Sep 2024 19:55:29 GMT
    End Date:	Tue, 24 Sep 2024 19:55:29 GMT
    ---------------------------------------------------
    
    [Error: Request failed with status code 401] {
      url: 'https://api.dune.com/api/v1/query/3996608/execute',
      method: 'POST',
      axiosError: 'invalid API Key',
      chain: 'ethereum'
    }

2024-10-09 09:45 UTC, g1nt0ki commented
@JCollinsX can you update the adapter to instead rely on event logs and compute data onchain? if you share contract/event details, I can implement it

2024-12-11 10:16 UTC, g1nt0ki commented
bump

2025-05-01 13:28 UTC, closed without merging