add avalon-finance-cedefi
DefiLlama/dimension-adapters pull request #1989
Opened 2024-10-12 04:38 UTC by jasmin-avalon

Trying to add Fee & Revenue for Avalon Labs CeDeFi. But it does not as expected. Looking for help. 

Fee & Revenue Mythology:  **Total Debt * Protocol Interest Rate.** 

OnChain Query
- CeDeFi Pool Address: `0xF95308B15E45BFF3d0811B5732d17Eb2A555afB2`
- Call `getPoolManagerReserveInformation` to get `debt` 
- Call `getPoolManagerConfig` to get `DEFAULT_POOL_INTEREST_RATE` 

----

Tried to build a fee and revenue adapter. But cannot pass the test. 

Error log:

```
[Error: Failed to call: function getPoolManagerConfig() view returns (tuple(uint256 DEFAULT_LTV, uint256 DEFAULT_LIQUIDATION_THRESHOLD, uint256 DEFAULT_POOL_INTEREST_RATE, uint256 DEFAULT_PROTOCOL_INTEREST_RATE, address USDT, address FBTC0, address FBTC1, address FBTCOracle, address AvalonUSDTVault, address AntaphaUSDTVault)) target: 0xF95308B15E45BFF3d0811B5732d17Eb2A555afB2 on chain: [ethereum] rpc: https://eth.llamarpc.com, https://rpc.ankr.com/eth, https://cloudflare-eth.com, https://ethereum-rpc.publicnode.com, https://1rpc.io/eth, https://rpc.mevblocker.io, https://rpc.flashbots.net, https://virginia.rpc.blxrbdn.com, https://uk.rpc.blxrbdn.com, https://singapore.rpc.blxrbdn.com, https://eth.rpc.blxrbdn.com, https://eth-mainnet.public.blastapi.io, https://api.securerpc.com/v1, https://eth-pokt.nodies.app, https://eth-mainnet-public.unifra.io, https://ethereum.blockpi.network/v1/rpc/public, https://rpc.payload.de, https://core.gashawk.io/rpc, https://eth.meowrpc.com, https://eth.drpc.org, https://mainnet.gateway.tenderly.co, https://gateway.tenderly.co/public/mainnet, https://eth.merkle.io, https://eth.nodeconnect.org, https://ethereum.rpc.subquery.network/public, https://rpc.graffiti.farm, https://rpc.public.curie.radiumblock.co/http/ethereum, https://eth-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f, https://rpc.public.curie.radiumblock.co/ws/ethereum, https://rpc.flashbots.net/fast, https://rpc.mevblocker.io/fast, https://rpc.mevblocker.io/noreverts, https://rpc.mevblocker.io/fullprivacy  call reverted, reason: fragment.format is not a function   ] {
  _underlyingError: 'TypeError: fragment.format is not a function',
  _isCustomError: true,
  chain: 'ethereum'
}
```

2024-10-12 04:40 UTC, llamatester commented
The avalon-finance-cedefi adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees avalon-finance-cedefi
    
    🦙 Running AVALON-FINANCE-CEDEFI adapter 🦙
    ---------------------------------------------------
    Start Date:	Fri, 11 Oct 2024 02:09:12 GMT
    End Date:	Sat, 12 Oct 2024 02:09:12 GMT
    ---------------------------------------------------
    
    [Error: Failed to call: function getPoolManagerConfig() view returns (tuple(uint256 DEFAULT_LTV, uint256 DEFAULT_LIQUIDATION_THRESHOLD, uint256 DEFAULT_POOL_INTEREST_RATE, uint256 DEFAULT_PROTOCOL_INTEREST_RATE, address USDT, address FBTC0, address FBTC1, address FBTCOracle, address AvalonUSDTVault, address AntaphaUSDTVault)) target: 0xF95308B15E45BFF3d0811B5732d17Eb2A555afB2 on chain: [ethereum] rpc: https://eth.llamarpc.com, https://rpc.ankr.com/eth, https://cloudflare-eth.com, https://ethereum-rpc.publicnode.com, https://1rpc.io/eth, https://rpc.mevblocker.io, https://rpc.flashbots.net, https://virginia.rpc.blxrbdn.com, https://uk.rpc.blxrbdn.com, https://singapore.rpc.blxrbdn.com, https://eth.rpc.blxrbdn.com, https://eth-mainnet.public.blastapi.io, https://api.securerpc.com/v1, https://eth-pokt.nodies.app, https://eth-mainnet-public.unifra.io, https://ethereum.blockpi.network/v1/rpc/public, https://rpc.payload.de, https://core.gashawk.io/rpc, https://eth.meowrpc.com, https://eth.drpc.org, https://mainnet.gateway.tenderly.co, https://gateway.tenderly.co/public/mainnet, https://eth.merkle.io, https://eth.nodeconnect.org, https://ethereum.rpc.subquery.network/public, https://rpc.graffiti.farm, https://eth-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f, https://rpc.flashbots.net/fast, https://rpc.mevblocker.io/fast, https://rpc.mevblocker.io/noreverts, https://rpc.mevblocker.io/fullprivacy  call reverted, reason: fragment.format is not a function   ] {
      _underlyingError: 'TypeError: fragment.format is not a function',
      _isCustomError: true,
      chain: 'ethereum'
    }

2024-10-14 13:52 UTC, g1nt0ki commented on fees/avalon-finance-cedefi/index.ts
> +const poolAddress = '0xF95308B15E45BFF3d0811B5732d17Eb2A555afB2'
this is not a valid contract?

2024-10-14 13:53 UTC, g1nt0ki commented on fees/avalon-finance-cedefi/index.ts
> +const poolAddress = '0xF95308B15E45BFF3d0811B5732d17Eb2A555afB2'
I have pushed a change where the contract is changed to one used in tvl repo, please fix it if it is wrong

2024-10-14 13:54 UTC, g1nt0ki commented on fees/avalon-finance-cedefi/index.ts
> +				dailyRevenue.addUSDValue(amount)
also, why is fees = revenue? isnt any part of the interest given to the lender? https://docs.llama.fi/list-your-project/other-dashboards/dimensions

2024-10-14 13:54 UTC, g1nt0ki requested changes
.

2024-10-14 13:56 UTC, g1nt0ki commented on fees/avalon-finance-cedefi/index.ts
> +const poolAddress = '0x02feDCff97942fe28e8936Cdc3D7A480fdD248f0'
please correct this address if it is incorrect

2024-10-28 07:47 UTC, closed without merging