Bonzo finance
DefiLlama/dimension-adapters pull request #2042
Opened 2024-10-28 12:44 UTC by bugbytesinc

Thankyou for accepting our general adapter PR, here is a proposed dimension adapter PR

---
##### Name (to be shown on DefiLlama):
Bonzo Finance

##### Twitter Link:
https://x.com/bonzo_finance

##### List of audit links if any:
https://docs.bonzo.finance/hub/resources/audits

##### Website Link:
https://bonzo.finance/

##### Logo (High resolution, will be shown with rounded borders):

##### Current TVL:
0

##### Treasury Addresses (if the protocol has treasury)
0x00000000000000000000000000000000005dc4d4

##### Chain:
295

##### Coingecko ID (so your TVL can appear on Coingecko, leave empty if not listed):

##### Coinmarketcap ID (so your TVL can appear on Coinmarketcap, leave empty if not listed):

##### Short Description (to be shown on DefiLlama):
The Liquidity Layer of Hedera: An open source, non-custodial lending protocol based on Aave.

##### Token address and ticker if any:

##### Category (full list at https://defillama.com/categories) *Please choose only one:
Lending

##### Oracle Provider(s): Specify the oracle(s) used (e.g., Chainlink, Band, API3, TWAP, etc.):
Supra Oracle

##### Implementation Details: Briefly describe how the oracle is integrated into your project:
Bonzo Finance uses Supra’s push oracles; these oracles feed asset price information at regular intervals to the Hedera network and enable the Bonzo Finance protocol to query the most recent or historical data.

##### Documentation/Proof: Provide links to documentation or any other resources that verify the oracle's usage:
https://docs.bonzo.finance/hub/developer/oracles/supra 

##### forkedFrom (Does your project originate from another project):
Aave

##### methodology (what is being counted as tvl, how is tvl being calculated): The calculated TVL is the current USD sum of deposits minus borrows for all all reserves found under https://app.bonzo.finance/

##### Github org/user (Optional, if your code is open source, we can track activity):
https://github.com/Bonzo-Labs

2024-10-28 12:45 UTC, llamatester commented
The bonzo adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees bonzo
    
    🦙 Running BONZO adapter 🦙
    ---------------------------------------------------
    Start Date:	Sun, 27 Oct 2024 00:00:00 GMT
    End Date:	Mon, 28 Oct 2024 00:00:00 GMT
    ---------------------------------------------------
    
    HEDERA 👇
    Backfill start time: 28/10/2024
    End timestamp: 1730119513.15844 (2024-10-28T12:45:13.158Z)
    Daily fees: 0
    └─ Methodology: Intrest and Flash Loan fees plus liquidation bonuses in USD
    Daily user fees: 0
    └─ Methodology: Intrest and Flash Loan fees plus liquidation bonuses in USD
    Daily protocol revenue: 0
    └─ Methodology: Portion of intrest rate fees and flash loan fees to Protocol Treasury in USD
    Daily supply side revenue: 0
    └─ Methodology: Portion of intrest rate fees to liquidity providers in USD

2024-10-28 16:30 UTC, dtmkeng requested changes

2024-10-28 16:30 UTC, dtmkeng commented on fees/bonzo/index.ts
> +    const total_protocol_fees = BigNumber(res.total_protocol_fees.usd_wad);
value is it daily value ?

2024-10-28 16:47 UTC, bugbytesinc commented on fees/bonzo/index.ts
> +    const total_protocol_fees = BigNumber(res.total_protocol_fees.usd_wad);
Yes, if I understand your definition correctly.

It is the USD table value of the sum of the protocol fees sent to the protocol's treasury wallet for the past 24 hours from the time of call.

2024-10-28 16:51 UTC, dtmkeng commented on fees/bonzo/index.ts
> +    const total_protocol_fees = BigNumber(res.total_protocol_fees.usd_wad);
why it still 0 ?

2024-10-28 17:48 UTC, bugbytesinc commented on fees/bonzo/index.ts
> +    const total_protocol_fees = BigNumber(res.total_protocol_fees.usd_wad);
The protocol has not yet turned on borrowing, so there is no income generated yet.

2024-10-29 08:40 UTC, merged

2025-01-02 21:29 UTC, bugbytesinc commented
Hello, thankyou for merging our PR back in October.  We have enabled borrowing on our site, and when I test locally I receive the following output:

```
$ npm test fees bonzo

> adapters@1.0.0 test
> ts-node --transpile-only cli/testAdapter.ts fees bonzo

🦙 Running BONZO adapter 🦙
---------------------------------------------------
Start Date:     Wed, 01 Jan 2025 00:00:00 GMT
End Date:       Thu, 02 Jan 2025 00:00:00 GMT
---------------------------------------------------

HEDERA 👇
Backfill start time: 2/1/2025
End timestamp: 1735849266.8877 (2025-01-02T20:21:06.887Z)
Daily fees: 561
└─ Methodology: Intrest and Flash Loan fees plus liquidation bonuses in USD
Daily user fees: 561
└─ Methodology: Intrest and Flash Loan fees plus liquidation bonuses in USD
Daily protocol revenue: 66
└─ Methodology: Portion of intrest rate fees and flash loan fees to Protocol Treasury in USD
Daily supply side revenue: 495
└─ Methodology: Portion of intrest rate fees to liquidity providers in USD
```

However, when I go to information page for bonzo finance:

https://defillama.com/protocol/bonzo-finance

In the methodology section I do not see a link to "Fees and Revenue code", which I would have expected to take me to our adapter code. 

Is there something we might have missed or need to fix to ensure it displays correctly?

Would it be beneficial to start a new PR for this discussion (there are some typos to fix on our part as well)

Thank you for your time and guidance.

Bonzo Team