Nbala finance: dex fees and volume
DefiLlama/dimension-adapters pull request #2069
Opened 2024-11-04 01:11 UTC by yellowBirdy

2024-11-04 01:13 UTC, llamatester commented
The nabla adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs nabla
    
    🦙 Running NABLA adapter 🦙
    ---------------------------------------------------
    Start Date:	Sat, 02 Nov 2024 22:42:07 GMT
    End Date:	Sun, 03 Nov 2024 22:42:07 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 15/8/2024
    Daily fees: 101
    └─ Methodology: All fees comes from the user.
    Daily protocol revenue: 0
    └─ Methodology: Currently no fees are taken by the protocl.
    Daily user fees: 101
    └─ Methodology: User pays between 0.01% and 0.1% fees on each swap.
    Daily volume: 202.80 k
    End timestamp: 1730673726 (2024-11-03T22:42:06.000Z)
    
    
    BASE 👇
    Backfill start time: 12/9/2024
    Daily fees: 0
    └─ Methodology: All fees comes from the user.
    Daily revenue: 0
    Daily user fees: 0
    └─ Methodology: User pays between 0.01% and 0.1% fees on each swap.
    Daily volume: 0
    End timestamp: 1730673726 (2024-11-03T22:42:06.000Z)

2024-11-06 01:21 UTC, dtmkeng requested changes

2024-11-06 01:21 UTC, dtmkeng commented on dexs/nabla/index.ts
> +                dailyVolume.add(e.tokenOut, e.amountOut)
volume should count one side, i think should count only tokenOut

2024-11-06 01:21 UTC, dtmkeng commented on dexs/nabla/index.ts
> +                dailyVolume.add(e.tokenOut, e.amountOut)
volume should count one side, i think should count only tokenOut

2024-11-06 13:51 UTC, llamatester commented
The nabla adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs nabla
    
    🦙 Running NABLA adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 05 Nov 2024 11:19:51 GMT
    End Date:	Wed, 06 Nov 2024 11:19:51 GMT
    ---------------------------------------------------
    
    ARBITRUM 👇
    Backfill start time: 15/8/2024
    Daily fees: 276
    └─ Methodology: All fees comes from the user.
    Daily protocol revenue: 0
    └─ Methodology: Currently no fees are taken by the protocl.
    Daily user fees: 276
    └─ Methodology: User pays between 0.01% and 0.1% fees on each swap.
    Daily volume: 551.35 k
    End timestamp: 1730891990 (2024-11-06T11:19:50.000Z)
    
    
    BASE 👇
    Backfill start time: 12/9/2024
    Daily fees: 18
    └─ Methodology: All fees comes from the user.
    Daily revenue: 0
    Daily user fees: 18
    └─ Methodology: User pays between 0.01% and 0.1% fees on each swap.
    Daily volume: 0
    End timestamp: 1730891990 (2024-11-06T11:19:50.000Z)

2024-11-06 15:13 UTC, merged