add bulbaswap volume add fees
DefiLlama/dimension-adapters pull request #2072
Opened 2024-11-05 07:07 UTC by madwiki

2024-11-05 07:07 UTC, llamatester commented
The bulbaswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators bulbaswap
    
    🦙 Running BULBASWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 04 Nov 2024 00:00:00 GMT
    End Date:	Tue, 05 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    MORPH 👇
    Backfill start time: 1/8/2023
    NO METHODOLOGY SPECIFIED
    End timestamp: 1730764800 (2024-11-05T00:00:00.000Z)
    Total volume: 482.72 k
    Daily volume: 3.31 k
    Daily fees: 12
    Total fees: 1.65 k

2024-11-05 07:27 UTC, llamatester commented
The bulbaswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts aggregators bulbaswap
    
    🦙 Running BULBASWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Mon, 04 Nov 2024 00:00:00 GMT
    End Date:	Tue, 05 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    MORPH 👇
    Backfill start time: 22/10/2024
    NO METHODOLOGY SPECIFIED
    End timestamp: 1730764800 (2024-11-05T00:00:00.000Z)
    Total volume: 482.73 k
    Daily volume: 3.32 k
    Daily fees: 12
    Total fees: 1.65 k

2024-11-06 15:52 UTC, dtmkeng requested changes

2024-11-06 15:52 UTC, dtmkeng commented on aggregators/bulbaswap/index.ts
> +  uniswapDayDatas(first: 1, orderBy: date, orderDirection: desc) {
could you use query by Id, because if data not up to date will collect incorrect data

2024-11-14 13:49 UTC, dtmkeng commented
thank you for PR i make some change  https://github.com/DefiLlama/dimension-adapters/pull/2095

2024-11-14 13:49 UTC, closed without merging