spark totalVolume onboarding
DefiLlama/dimension-adapters pull request #2108
Opened 2024-11-20 09:23 UTC by PaulZhemanov

2024-11-20 09:24 UTC, llamatester commented
The spark adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs spark
    
    🦙 Running SPARK adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 19 Nov 2024 00:00:00 GMT
    End Date:	Wed, 20 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Trade Volume: 4794.2208423282755
    Timestamp: 1732093200
    FUEL 👇
    Backfill start time: 30/9/2020
    NO METHODOLOGY SPECIFIED
    Total volume: 4.79 k
    End timestamp: 1732093200 (2024-11-20T09:00:00.000Z)

2024-11-20 14:25 UTC, llamatester commented
The spark adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs spark
    
    🦙 Running SPARK adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 19 Nov 2024 00:00:00 GMT
    End Date:	Wed, 20 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    Trade Volume: 4813.46517827553
    Timestamp: 1732111200
    FUEL 👇
    Backfill start time: 30/9/2020
    NO METHODOLOGY SPECIFIED
    Total volume: 4.81 k
    End timestamp: 1732111200 (2024-11-20T14:00:00.000Z)

2024-11-20 15:24 UTC, dtmkeng commented
could you return dailyVolume ?

2024-11-20 15:25 UTC, dtmkeng requested changes

2024-11-20 15:25 UTC, dtmkeng commented on dexs/spark/index.ts
> +        totalVolume: totalVolume,
could you add dailyVolume ?

2024-11-21 09:53 UTC, llamatester commented
The spark adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs spark
    
    🦙 Running SPARK adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 20 Nov 2024 00:00:00 GMT
    End Date:	Thu, 21 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    FUEL 👇
    Backfill start time: 30/9/2020
    NO METHODOLOGY SPECIFIED
    Daily volume: 55
    End timestamp: 1732182780 (2024-11-21T09:53:00.000Z)

2024-11-21 09:55 UTC, PaulZhemanov commented
@llamatester Hi! could you check updates please?

2024-11-21 10:50 UTC, llamatester commented
The spark adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs spark
    
    🦙 Running SPARK adapter 🦙
    ---------------------------------------------------
    Start Date:	Wed, 20 Nov 2024 08:20:55 GMT
    End Date:	Thu, 21 Nov 2024 08:20:55 GMT
    ---------------------------------------------------
    
    FUEL 👇
    Backfill start time: 6/11/2024
    NO METHODOLOGY SPECIFIED
    Daily volume: 54
    End timestamp: 1732177254 (2024-11-21T08:20:54.000Z)

2024-11-21 10:56 UTC, merged

2024-11-21 10:56 UTC, g1nt0ki commented
@PaulZhemanov thanks for the PR