[emojicoin] Add fees
DefiLlama/dimension-adapters pull request #2140
Opened 2024-11-27 20:01 UTC by gregnazario

2024-11-27 20:01 UTC, llamatester commented
The emojicoin.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees emojicoin.ts
    
    🦙 Running EMOJICOIN.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 26 Nov 2024 00:00:00 GMT
    End Date:	Wed, 27 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    APTOS 👇
    Backfill start time: 3/4/2023
    NO METHODOLOGY SPECIFIED
    Total fees: 2547.51 B
    Daily fees: 8.00 B
    End timestamp: 1732665599 (2024-11-26T23:59:59.000Z)

2024-11-27 20:22 UTC, llamatester commented
The emojicoin.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees emojicoin.ts
    
    🦙 Running EMOJICOIN.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 26 Nov 2024 00:00:00 GMT
    End Date:	Wed, 27 Nov 2024 00:00:00 GMT
    ---------------------------------------------------
    
    APTOS 👇
    Backfill start time: 3/4/2023
    NO METHODOLOGY SPECIFIED
    Total fees: 304.94 k
    Daily fees: 958
    End timestamp: 1732665599 (2024-11-26T23:59:59.000Z)

2024-11-28 00:06 UTC, xbtmatt commented on helpers/aptops.ts
>  export const APTOS_PRC = 'https://aptos-mainnet.pontem.network';
```suggestion
export const APTOS_RPC = 'https://aptos-mainnet.pontem.network';
```

2024-11-28 00:06 UTC, xbtmatt commented on helpers/aptops.ts
> +        let url = `${APTOS_PRC}/v1/accounts/${account}/resources?limit=9999`
```suggestion
        let url = `${APTOS_RPC}/v1/accounts/${account}/resources?limit=9999`
```

2024-11-28 00:06 UTC, xbtmatt commented on fees/emojicoin.ts
> +        // TODO: revenue
The revenue just be the integrator fees

2024-11-28 12:57 UTC, 0xngmi commented on fees/emojicoin.ts
> +        // TODO: revenue
so fees = revenue?

2024-11-28 22:51 UTC, g1nt0ki commented on fees/emojicoin.ts
> +const fetch = async (timestamp: number) => {
change this to adapter version 2, then you get start and endTimestamp as part of input

2024-11-28 22:51 UTC, g1nt0ki commented on fees/emojicoin.ts
> +    const prices = await getPrices(["coingecko:aptos"], timestamp)
avoid pulling token prices and change code to something like [this](https://github.com/DefiLlama/dimension-adapters/blob/master/fees/milkyway.ts#L23)

2024-12-03 09:43 UTC, g1nt0ki requested changes
.

2024-12-11 21:29 UTC, closed without merging