add plunderswap dex volume
DefiLlama/dimension-adapters pull request #2197
Opened 2024-12-11 12:31 UTC by darthgus

add plunderswap dex volume

2024-12-11 12:32 UTC, llamatester commented
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 00:00:00 GMT
    End Date:	Wed, 11 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZILLIQA 👇
    Backfill start time: 10/12/2024
    Daily volume: 8.51 k
    └─ Methodology: Volume of trades on Plunderswap at the start of the day (12:00:00 UTC) for the previous day
    End timestamp: 1733788800 (2024-12-10T00:00:00.000Z)

2024-12-11 12:33 UTC, darthgus commented
@dtmkeng i apologize greatly for the previous PR issue.  wont happen again.

2024-12-11 14:45 UTC, dtmkeng requested changes

2024-12-11 14:45 UTC, dtmkeng commented on dexs/plunderswap/index.ts
> +    .reduce((closest, current) => {
i think you can filter time more than start time and less than end time instead before reduce

2024-12-11 15:11 UTC, llamatester commented
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 00:00:00 GMT
    End Date:	Wed, 11 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZILLIQA 👇
    Backfill start time: 10/12/2024
    Daily volume: 8.87 k
    └─ Methodology: Volume of trades on Plunderswap at the start of the day (12:00:00 UTC) for the previous day
    End timestamp: 1733788800 (2024-12-10T00:00:00.000Z)

2024-12-11 15:11 UTC, darthgus commented on dexs/plunderswap/index.ts
> +    .reduce((closest, current) => {
Ok good point, think I have implemented that correctly.

2024-12-11 23:26 UTC, llamatester commented
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 10 Dec 2024 00:00:00 GMT
    End Date:	Wed, 11 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZILLIQA 👇
    Backfill start time: 10/12/2024
    Daily volume: 8.98 k
    └─ Methodology: Volume of trades on Plunderswap at the start of the day (12:00:00 UTC) for the previous day
    End timestamp: 1733788800 (2024-12-10T00:00:00.000Z)

2024-12-13 01:11 UTC, llamabutler commented
The plunderswap adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts dexs plunderswap
    
    🦙 Running PLUNDERSWAP adapter 🦙
    ---------------------------------------------------
    Start Date:	Thu, 12 Dec 2024 00:00:00 GMT
    End Date:	Fri, 13 Dec 2024 00:00:00 GMT
    ---------------------------------------------------
    
    ZILLIQA 👇
    Backfill start time: 10/12/2024
    Daily volume: 5.38 k
    └─ Methodology: Volume of trades on Plunderswap at the start of the day (00:00:00 UTC) for the previous day
    End timestamp: 1733961600 (2024-12-12T00:00:00.000Z)

2024-12-13 01:13 UTC, darthgus commented
Having a look over my working out, i seen it was still inefficient, so have re-written it much more simpler now.    will give the exact value based on 00:00:00 entry. @dtmkeng

2024-12-13 09:25 UTC, merged