add goplus locker fee
DefiLlama/dimension-adapters pull request #2231
Opened 2024-12-18 06:21 UTC by goplusbot

2024-12-18 06:22 UTC, llamabutler commented
The goplus-locker.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees goplus-locker.ts
    
    🦙 Running GOPLUS-LOCKER.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 17 Dec 2024 03:51:32 GMT
    End Date:	Wed, 18 Dec 2024 03:51:32 GMT
    ---------------------------------------------------
    
    Error: INDEXA_DB not set
        at getConnection (/home/runner/work/dimension-adapters/dimension-adapters/helpers/indexer.ts:10:24)
        at queryIndexer (/home/runner/work/dimension-adapters/dimension-adapters/helpers/indexer.ts:30:22)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/goplus-locker.ts:28:45)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 4)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:84:21 {
      chain: 'gravity'
    }

2024-12-18 06:29 UTC, llamabutler commented
The goplus-locker.ts adapter exports:
        
 
 
    > adapters@1.0.0 test
    > ts-node --transpile-only cli/testAdapter.ts fees goplus-locker.ts
    
    🦙 Running GOPLUS-LOCKER.TS adapter 🦙
    ---------------------------------------------------
    Start Date:	Tue, 17 Dec 2024 03:58:42 GMT
    End Date:	Wed, 18 Dec 2024 03:58:42 GMT
    ---------------------------------------------------
    
    Error: INDEXA_DB not set
        at getConnection (/home/runner/work/dimension-adapters/dimension-adapters/helpers/indexer.ts:10:24)
        at queryIndexer (/home/runner/work/dimension-adapters/dimension-adapters/helpers/indexer.ts:30:22)
        at fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/goplus-locker.ts:28:45)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async getChainResult (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:51:18)
        at async Promise.all (index 0)
        at async runAdapter (/home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:27:20)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:84:21 {
      chain: 'ethereum'
    }

2024-12-18 13:10 UTC, dtmkeng requested changes

2024-12-18 13:10 UTC, dtmkeng commented on fees/goplus-locker.ts
> +    const transfer_logs = await queryIndexer(`
our index it support only eth chain

2024-12-19 14:44 UTC, merged

2024-12-19 16:39 UTC, dtmkeng commented
@goplusbot  goplus-locker is it sub protocol of this https://defillama.com/protocol/goplus-security#information ?

2025-02-18 17:24 UTC, dtmkeng commented
okay will list