add zkSync Era to Fees/Revenue dashboard
DefiLlama/dimension-adapters pull request #760
Opened 2023-08-21 17:11 UTC by lgingerich

FYI: had trouble with local testing

2023-08-21 18:19 UTC, llamatester commented
The zksync-era adapter exports: 
        
 
 _______________________________________
    Fees for 20/8/2023
    _______________________________________
    
    Failed to get value on era: Error: Payment Required
    ERA 👇
    Timestamp attempted: 19/8/2023
    Error: Payment Required
        at retries (/home/runner/work/dimension-adapters/dimension-adapters/helpers/flipsidecrypto.ts:55:29)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async queryFlipside (/home/runner/work/dimension-adapters/dimension-adapters/helpers/flipsidecrypto.ts:11:10)
        at async fetch (/home/runner/work/dimension-adapters/dimension-adapters/fees/zksync-era/index.ts:23:28)
        at async /home/runner/work/dimension-adapters/dimension-adapters/adapters/utils/runAdapter.ts:32:52
        at async Promise.allSettled (index 0)
        at async /home/runner/work/dimension-adapters/dimension-adapters/cli/testAdapter.ts:52:23
    
    
    
    
    Done in 4033.35s.

2023-08-22 11:23 UTC, dtmkeng requested changes

2023-08-22 11:23 UTC, dtmkeng commented on fees/zksync-era/index.ts
> +          const startblock = (await getBlock(fromTimestamp, CHAIN.ERA, {}));
use era block query on eth index is it correct ?

2023-08-22 13:01 UTC, lgingerich commented on fees/zksync-era/index.ts
> +          const startblock = (await getBlock(fromTimestamp, CHAIN.ERA, {}));
Are you asking if the `getBlock()` usage is correct?

I copied it from the Arbitrum adapter and I don't see anything here or in the function definition that would prevent it from working.

2023-08-22 13:10 UTC, dtmkeng commented on fees/zksync-era/index.ts
> +          const startblock = (await getBlock(fromTimestamp, CHAIN.ERA, {}));
i mean you use block number of era query index eth
for arb it  use for query withdraw fees when team withdraw fees on fees wallet

2023-08-22 13:18 UTC, lgingerich commented on fees/zksync-era/index.ts
> +          const startblock = (await getBlock(fromTimestamp, CHAIN.ERA, {}));
Oh I see what you mean now — will fix. Thanks

2023-08-22 13:55 UTC, dtmkeng commented
i think fees get from eth is not correct is there way to get on chain fees ?

2023-08-22 14:13 UTC, merged

2023-08-22 14:17 UTC, dtmkeng commented
do you have result at yestday ? will verify result before live

2023-08-22 14:25 UTC, lgingerich commented
This is aggregated by month and should be pretty accurate. https://dune.com/niftytable/rollup-economics