Putting bluefin daily volume DEX adaptor
DefiLlama/dimension-adapters pull request #885
Opened 2023-10-11 20:15 UTC by singhalhemant

Putting bluefin daily volume DEX adaptor

2023-10-11 20:15 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 10/10/2023
    _______________________________________
    
    Version -> SUI
    ---------
    SUI 👇
    Backfill start time: 27/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 7104326.151
    Timestamp: 1696982399
    
    
    Version -> ARB
    ---------
    ARBITRUM 👇
    Backfill start time: 27/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 6252271.016600002
    Timestamp: 1696982399
    
    
    Done in 6.11s.

2023-10-11 20:57 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 10/10/2023
    _______________________________________
    
    Version -> SUI
    ---------
    SUI 👇
    Backfill start time: 27/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 8120550.3582
    Timestamp: 1696982399
    
    
    Version -> ARB
    ---------
    ARBITRUM 👇
    Backfill start time: 27/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 7058168.5669
    Timestamp: 1696982399
    
    
    Done in 5.92s.

2023-10-11 20:57 UTC, singhalhemant commented
Moved to using marketdata API

2023-10-11 21:26 UTC, YameenMalik requested changes

2023-10-11 21:26 UTC, YameenMalik commented on dexs/bluefin/index.ts
> +  baseURL = `${baseURL}` + `?symbol=${product}`;
please change this to `${baseURL}?symbol=${product}`;

2023-10-11 21:26 UTC, YameenMalik commented on dexs/bluefin/index.ts
> +const computeVolume = async (timestamp: number, baseUrl: string, productIds: string[]) => {
Please define a return type for the method.  It is best to create an interface at the top for the return type:
```
return {
    totalVolume: undefined,
    dailyVolume: dailyVolume ? `${dailyVolume}` : undefined,
    timestamp: timestamp,
  };
  ```
  Something like:
  ```
  interface Volume {
     totalVolume: number | undefined,
     dailyVolume: number | undefined,
     timestamp: number,     
  }
  ```

2023-10-11 21:26 UTC, YameenMalik commented on dexs/bluefin/index.ts
> +const startTime = 1695857191;
define constant in `CAPITAL_CASE`

2023-10-11 21:26 UTC, YameenMalik commented on dexs/bluefin/index.ts
> +const startTime = 1695857191;
what is this time by the way? would be good to add a comment. I assume its the time at which trading on Sui began.

2023-10-11 21:41 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 10/10/2023
    _______________________________________
    
    Version -> SUI
    ---------
    SUI 👇
    Backfill start time: 27/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 8081431.164000001
    Timestamp: 1696982399
    
    
    Version -> ARB
    ---------
    ARBITRUM 👇
    Backfill start time: 27/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 7053238.391799999
    Timestamp: 1696982399
    
    
    Done in 5.12s.

2023-10-11 21:45 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 10/10/2023
    _______________________________________
    
    Version -> SUI
    ---------
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 8073534.4944
    Timestamp: 1696982399
    
    
    Version -> ARB
    ---------
    ARBITRUM 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 7046081.088399999
    Timestamp: 1696982399
    
    
    Done in 5.40s.

2023-10-11 22:06 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 10/10/2023
    _______________________________________
    
    Version -> SUI
    ---------
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 8075989.1836
    Timestamp: 1696982399
    
    
    Version -> ARB
    ---------
    ARBITRUM 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 7046142.5101
    Timestamp: 1696982399
    
    
    Done in 4.76s.

2023-10-11 22:13 UTC, YameenMalik approved these changes

2023-10-12 08:51 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 11/10/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    ARBITRUM 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 4120592.088
    Timestamp: 1697068799
    
    
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 7231390.791300001
    Timestamp: 1697068799
    
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 4120592.088
    Timestamp: 1697068799
    
    
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 7231390.791300001
    Timestamp: 1697068799
    
    
    Done in 5.46s.

2023-10-12 10:38 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 11/10/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    ARBITRUM 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 4538568.897
    Timestamp: 1697068799
    
    
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 7396416.920700001
    Timestamp: 1697068799
    
    
    Done in 4.23s.

2023-10-12 14:49 UTC, dtmkeng commented
seem symbol your config is perp is it DERIVATIVES volume ? 
not swap, swap mean spot or swap direct to LP ?

2023-10-12 15:32 UTC, singhalhemant commented
Hi @dtmkeng , 

Thanks for your comment. We need our volume 24h to be available in this dashboard as well https://defillama.com/chain/Sui (against bluefin). 

Will it be ok if I move the config to derivatives? 

We are a trading exchange which supports perp for now but have plans to add spots soon as well.

2023-10-12 15:51 UTC, dtmkeng commented
> Hi @dtmkeng ,
> 
> Thanks for your comment. We need our volume 24h to be available in this dashboard as well https://defillama.com/chain/Sui (against bluefin).
> 
> Will it be visible in "Volume 24h" column if I move the config to derivatives?
> 
> We are a trading exchange which supports perp for now but have plans to add spots soon as well.
this page  volume volume 24h I guess supply swap volume 
if you need list DERIVATIVES volume it show only this page https://defillama.com/derivatives
and toggle like this 
<img width="455" alt="image" src="https://github.com/DefiLlama/dimension-adapters/assets/11234402/d210a6b4-8e6c-41c4-8bcb-47903397fe62">

2023-10-12 16:38 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 11/10/2023
    _______________________________________
    
    Version -> SWAP
    ---------
    ARBITRUM 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 4609461.236200001
    Timestamp: 1697068799
    
    
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 3543628.4166
    Timestamp: 1697068799
    
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 4609461.236200001
    Timestamp: 1697068799
    
    
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 3543628.4166
    Timestamp: 1697068799
    
    
    Done in 5.80s.

2023-10-12 16:42 UTC, singhalhemant commented
Hi @dtmkeng ,

Thanks for your guidance. Checked and it would be good to have it in both given we are a trading protocol. 

Made this quick change and will really appreciate if you could please approve and merge! 

"this page volume volume 24h I guess supply swap volume
if you need list DERIVATIVES volume it show only this page https://defillama.com/derivatives
and toggle like this"

2023-10-12 17:18 UTC, dtmkeng commented
> Hi @dtmkeng ,
> 
> Thanks for your guidance. Checked and it would be good to have it in both given we are a trading protocol.
> 
> Made this quick change and will really appreciate if you could please approve and merge!
> 
> "this page volume volume 24h I guess supply swap volume if you need list DERIVATIVES volume it show only this page https://defillama.com/derivatives and toggle like this"

your API is have swap volume ?

2023-10-12 17:18 UTC, dtmkeng commented
seem `PRODUCT_CONFIG` is perp

2023-10-12 17:19 UTC, dtmkeng commented
and if you have one type volume plx add only one breakdown

2023-10-14 15:44 UTC, llamatester commented
The bluefin adapter exports: 
        
 
 _______________________________________
    Dexs for 13/10/2023
    _______________________________________
    
    Version -> DERIVATIVES
    ---------
    ARBITRUM 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 4224060.9303
    Timestamp: 1697241599
    
    
    SUI 👇
    Backfill start time: 25/9/2023
    NO METHODOLOGY SPECIFIED
    Total volume: undefined
    Daily volume: 1805908.102
    Timestamp: 1697241599
    
    
    Done in 4.84s.

2023-10-14 15:52 UTC, singhalhemant commented
Hi @dtmkeng , 

Yes sure. For now, I have removed swap and going with derivatives so that this PR could be merged. 

Will really appreciate if it can be merged now please.

2023-10-14 16:53 UTC, merged